/*
 *
 * WomanPage constants
 *
 */

export const LOAD_WOMAN_SHIRT_PRODUCTS = 'app/HomePage/LOAD_WOMAN_SHIRT_PRODUCTS';
export const LOAD_WOMAN_SHIRT_PRODUCTS_SUCCESS = 'app/HomePage/LOAD_WOMAN_SHIRT_PRODUCTS_SUCCESS';
export const LOAD_WOMAN_SHIRT_PRODUCTS_ERROR = 'app/HomePage/LOAD_WOMAN_SHIRT_PRODUCTS_ERROR';



export const LOAD_WOMAN_JEANS_PRODUCTS = 'app/HomePage/LOAD_WOMAN_JEANS_PRODUCTS';
export const LOAD_WOMAN_JEANS_PRODUCTS_SUCCESS = 'app/HomePage/LOAD_WOMAN_JEANS_PRODUCTS_SUCCESS';
export const LOAD_WOMAN_JEANS_PRODUCTS_ERROR = 'app/HomePage/LOAD_WOMAN_JEANS_PRODUCTS_ERROR';
