/*
 *
 * ManPage constants
 *
 */

export const LOAD_MAN_SHIRT_PRODUCTS = 'app/HomePage/LOAD_MAN_SHIRT_PRODUCTS';
export const LOAD_MAN_SHIRT_PRODUCTS_SUCCESS = 'app/HomePage/LOAD_MAN_SHIRT_PRODUCTS_SUCCESS';
export const LOAD_MAN_SHIRT_PRODUCTS_ERROR = 'app/HomePage/LOAD_MAN_SHIRT_PRODUCTS_ERROR';



export const LOAD_MAN_JEANS_PRODUCTS = 'app/HomePage/LOAD_MAN_JEANS_PRODUCTS';
export const LOAD_MAN_JEANS_PRODUCTS_SUCCESS = 'app/HomePage/LOAD_MAN_JEANS_PRODUCTS_SUCCESS';
export const LOAD_MAN_JEANS_PRODUCTS_ERROR = 'app/HomePage/LOAD_MAN_JEANS_PRODUCTS_ERROR';